### ISSUE TITLE
Récupéré les Lauches

### ISSUE THREAD

**Issue by RedHotMan** [Ionic-SpaceX/SpaceX#2]
### To Do

- [x] Get All launches
   - [x] Manage filters
- [x] Get Past launches
- [x] Get Upcoming launches
- [x] Get Next launches

- [x] List Past Launches
- [ ] List Upcoming Launches
- [x] Add filters
     - [x] Launch year `launch_year`
     - [x] Rocket `rocket_id`
     - [x] ? `core_reuse`
     - [ ] ? `core_serial`

**Comment by RedHotMan** [comment]
@gursingh93  @CNadjim 
Sur quelles filtres vous voulez qu'on se concentre en premier lieu ? 
Sachant que lorsqu'on en a fait un, le reste coule de source.

See la [liste des filtres](https://github.com/r-spacex/SpaceX-API/wiki/Launches#query-string-options)

**Comment by gurnavdeep** [comment]
@RedHotMan @CNadjim 
Pour les filtres on va partir sur les filtres ayant le plus d'importance à mon avis.
Donc on va dire sur Order (ascendant et descendant), reused et enfin launch_year.

Ensuite si l'on en trouve d'autres on en rajoutera par la suite :100:
